#!/bin/bash -e

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-grpckit}
GRPC_VERSION=${GRPC_VERSION:-1.51.0}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.51.0}
GRPC_WEB_VERSION=${GRPC_WEB_VERSION:-1.4.2}
BUILD_VERSION=${BUILD_VERSION:-1}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${LATEST:false}
BUF_VERSION=${BUF_VERSION:-1.9.0}
BUILDS=("grpckit" "protoc" "buf" "omniproto")
