#!/bin/bash -e

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-grpckit}
LIBPROTOC_VERSION=${LIBPROTOC_VERSION:-22.2} # This now versioned to match the compiler version number
GRPC_VERSION=${GRPC_VERSION:-1.53.0}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.54.0}
GRPC_WEB_VERSION=${GRPC_WEB_VERSION:-1.4.2}
BUILD_VERSION=${BUILD_VERSION:-1}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${LATEST:false}
BUF_VERSION=${BUF_VERSION:-1.16.0}
BUILDS=("grpckit" "protoc" "buf" "omniproto")
