name: Docker Image CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:

  build-grpckit-build-arm64:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v2  # https://github.com/docker/setup-qemu-action
        with:
          platforms: linux/arm64,linux/amd64
      - uses: docker/setup-buildx-action@v1 # https://github.com/docker/setup-buildx-action
        with:
          version: v0.7.0 # https://github.com/docker/build-push-action/issues/517#issuecomment-995863001
      - name: Earthly version
        run: earthly --org grpckit --sat grpckit-arm-satellite --platform linux/arm64 --version
      - name: Run build
        run: earthly --org grpckit --sat grpckit-arm-satellite -P --push --platform linux/arm64 +grpckit-build

  build-grpckit-build-amd64:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v2  # https://github.com/docker/setup-qemu-action
        with:
          platforms: linux/arm64,linux/amd64
      - uses: docker/setup-buildx-action@v1 # https://github.com/docker/setup-buildx-action
        with:
          version: v0.7.0 # https://github.com/docker/build-push-action/issues/517#issuecomment-995863001
      - name: Earthly version
        run: earthly --org grpckit --sat grpckit-amd-satellite --platform linux/amd64 --version
      - name: Run build
        run: earthly --org grpckit --sat grpckit-amd-satellite -P --push --platform linux/amd64 +grpckit-build

  build-all-omniproto:
    runs-on: ubuntu-latest
    needs:
      - build-grpckit-build-arm64
      - build-grpckit-build-amd64
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v2  # https://github.com/docker/setup-qemu-action
        with:
          platforms: linux/arm64,linux/amd64
      - uses: docker/setup-buildx-action@v1 # https://github.com/docker/setup-buildx-action
        with:
         version: v0.7.0 # https://github.com/docker/build-push-action/issues/517#issuecomment-995863001
      - name: Earthly version
        run: earthly --org grpckit --sat grpckit-arm-satellite --version
      - name: Run build
        run: earthly --org grpckit --sat grpckit-arm-satellite -P --push +build-all-omniproto

  build-all-protoc:
    runs-on: ubuntu-latest
    needs:
      - build-grpckit-build-arm64
      - build-grpckit-build-amd64
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v2  # https://github.com/docker/setup-qemu-action
        with:
          platforms: linux/arm64,linux/amd64
      - uses: docker/setup-buildx-action@v1 # https://github.com/docker/setup-buildx-action
        with:
         version: v0.7.0 # https://github.com/docker/build-push-action/issues/517#issuecomment-995863001
      - name: Earthly version
        run: earthly --org grpckit --sat grpckit-arm-satellite --version
      - name: Run build
        run: earthly --org grpckit --sat grpckit-arm-satellite -P --push +build-all-protoc
